### EXP 1 : Machine Learning Experiment-1 (Numpy Code)
### Name : Manav Lakhani
### Roll No. : 35

In [3]:
## Program-1 : To practice python numpy functions.
import numpy as np

In [4]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])    
print(f"Array from list: {array_1d}")

Array from list: [1 2 3 4 5]


In [5]:
#Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n {array_2d}")

2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
#using arange, linescpace, zeros, ones, eye
arr_arrange = np.arange(0, 10, 2)
print(f"Arange Array : {arr_arrange}")

Arange Array : [0 2 4 6 8]


In [7]:
arr_linespace = np.linspace(0, 1, 5)
print(f"Linespace Array : {arr_linespace}")

Linespace Array : [0.   0.25 0.5  0.75 1.  ]


In [8]:
arr_zeors = np.zeros((2, 3))
print(f"Zeros Array : \n{arr_zeors}")

Zeros Array : 
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
arr_ones = np.ones((3, 2), dtype=int)
print(f"Ones Array : \n{arr_ones}")

Ones Array : 
[[1 1]
 [1 1]
 [1 1]]


In [14]:
arr_eye = np.eye(3, dtype=int)
print(f"Identity Matrix : \n{arr_eye}")

Identity Matrix : 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
# Array Attributes
print(f"Shape of 2D Array: {array_2d.shape}")
print(f"Size of 2D Array : {array_2d.size}")
print(f"Dimensions of 2D Array : {array_2d.ndim}")
print(f"Data type of 2D Array : {array_2d.dtype}")
print(f"Item size of 2D Array : {array_2d.itemsize} bytes")

Shape of 2D Array: (2, 3)
Size of 2D Array : 6
Dimensions of 2D Array : 2
Data type of 2D Array : int64
Item size of 2D Array : 8 bytes


In [17]:
#Indexing and Slicing
arr = np.array([10, 20, 30, 40, 50])
print(f"Original Array: {arr}")
print(f"Element at index 2: {arr[2]}")
print(F"Last Element: {arr[-1]}")
print(f"Sliced Array (1 to 4): {arr[1:4]}")

Original Array: [10 20 30 40 50]
Element at index 2: 30
Last Element: 50
Sliced Array (1 to 4): [20 30 40]


In [18]:
# 2D Array Slicing
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"Original 2D Array:\n{arr2d}")
print(f"First Row: {arr2d[0, :]}")
print(f"Second column: {arr2d[:, 1]}")
print(f"Sunmatrix : \n{arr2d[0:2, 1:3]}")

Original 2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
First Row: [10 20 30]
Second column: [20 50 80]
Sunmatrix : 
[[20 30]
 [50 60]]


In [19]:
# Basic Operations
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a ** 2:", a**2)

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a ** 2: [1 4 9]


In [20]:
#Broadcasting
c = np.array([[1,2,3], [4,5,6]])
d = np.array([1,1,1])
print("Broadcasting result:\n", c + d)

Broadcasting result:
 [[2 3 4]
 [5 6 7]]


In [25]:
# Universal Functions
arr = np.array([1,4,9, 16])
print("sqrt:", np.sqrt(arr))
print("exp:", np.exp(arr))
print("log:", np.log(arr))
print("sin:", np.sin(arr))
print("cos:", np.cos(arr))

sqrt: [1. 2. 3. 4.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
log: [0.         1.38629436 2.19722458 2.77258872]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
cos: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [27]:
# Aggreation Functions
arr = np.array([[1,2,3],[4,5,6]])
print("Sum:", np.sum(arr))
print("Sum axis 0:", np.sum(arr, axis=0))
print("Sum axis 1:", np.sum(arr, axis=1))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Argmax:", np.argmax(arr))
print("Argmin:", np.argmin(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 21
Sum axis 0: [5 7 9]
Sum axis 1: [ 6 15]
Mean: 3.5
Max: 6
Min: 1
Argmax: 5
Argmin: 0
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665


In [28]:
# Reshaping and Flattenting
arr = np.arange(12)
print("Original array:", arr)
arr_reshaped = arr.reshape(3,4)
print("Reshaped 3x4 array:\n", arr_reshaped)
arr_flat = arr_reshaped.flatten()
print("Flattened array:", arr_flat)
arr_transpose = arr_reshaped.T
print("Transpose:\n", arr_transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [31]:
# Stacking and Splitting
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Horizontal stack:", np.hstack((a,b)))
print("Vertical stack:\n", np.vstack((a,b)))

arr = np.arange(9)
print("Original array:", arr)
print("Split into 3 parts:", np.split(arr, 3))

Horizontal stack: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Original array: [0 1 2 3 4 5 6 7 8]
Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [32]:
#  Copy V/S View
arr = np.array([1,2,3,4])
arr_view = arr.view()
arr_copy = arr.copy()
arr_view[0] = 100
arr_copy[1] = 200
print("Original after view change:", arr)
print("Original after copy change:", arr)

Original after view change: [100   2   3   4]
Original after copy change: [100   2   3   4]


In [33]:
# Boolean Indexing & Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])
print(f"Elements > 25 : {arr[arr > 25]}")
indices = [0,2,4]
print(f"Fancy indexing : {arr[indices]}")

Elements > 25 : [30 40 50]
Fancy indexing : [10 30 50]


In [34]:
# Random
rand_arr = np.random.rand(3,3) # uniform [0,1)
print("Random array:\n", rand_arr)

rand_int = np.random.randint(0,10,5)
print("Random integers:", rand_int)

normal_arr = np.random.randn(3,3) # standard normal
print("Normal distribution array:\n", normal_arr)

Random array:
 [[0.41073604 0.67076533 0.62075838]
 [0.15652671 0.86915983 0.06934301]
 [0.26483984 0.91295792 0.5062353 ]]
Random integers: [4 5 9 4 6]
Normal distribution array:
 [[ 0.01065909 -0.32120284 -0.43255924]
 [-0.37445828  1.22710403 -2.00119701]
 [ 0.68229239  0.26615454 -0.41242608]]


In [35]:
# Linear Algebra Functions
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix multiplication:\n", np.dot(A,B))
print("Matrix determinant:", np.linalg.det(A))
print("Matrix inverse:\n", np.linalg.inv(A))
print("Eigenvalues and Eigenvectors:\n", np.linalg.eig(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix determinant: -2.0000000000000004
Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and Eigenvectors:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [36]:
# 13. Saving and Loading Arrays
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

print("\nAll major NumPy functions executed successfully!")

Loaded array: [10 20 30 40 50]

All major NumPy functions executed successfully!
